export default {
  ERROR_TOKEN_MISSING: "ERROR_TOKEN_MISSING",
  ERROR_INVALID_TOKEN: "ERROR_INVALID_TOKEN",
  ERROR_INTERNAL_SERVER_ERROR: "ERROR_INTERNAL_SERVER_ERROR",
  ERROR_FIELD_TASK_MISSING: "ERROR_TASK_MISSING",
  ERROR_FIELD_TASK_ID_MISSING: "ERROR_TASK_ID_MISSING",
  ERROR_NO_SUCH_TASK_FOUND_WITH_ID: "ERROR_NO_SUCH_TASK_FOUND_WITH_ID",
  ERROR_INVALID_FIELD: "ERROR_INVALID_FIELD",
  ERROR_SUCH_SORTING_NOT_FOUND: "ERROR_SUCH_SORTING_NOT_FOUND",
  ERROR_EMAIL_ALREADY_IN_USE: "ERROR_EMAIL_ALREADY_EXISTS",
  ERROR_INVALID_EMAIL: "ERROR_INVALID_EMAIL",
  ERROR_INVALID_NAME: "ERROR_INVALID_NAME",
  ERROR_INVALID_PASSWORD: "ERROR_INVALID_PASSWORD",
  ERROR_INVALID_LASTNAME: "ERROR_INVALID_LASTNAME",
  ERROR_FIELDS_EMAIL_MALFORMED_OR_MISSING:
    "ERROR_FIELDS_EMAIL_MALFORMED_OR_MISSING",
  ERROR_FIELDS_PASSWORD_MALFORMED_OR_MISSING:
    "ERROR_FIELDS_PASSWORD_MALFORMED_OR_MISSING",
  ERROR_INVALID_EMAIL_OR_PASSWORD: "ERROR_INVALID_EMAIL_OR_PASSWORD",
  ERROR_NO_SUCH_USER_FOUND: "ERROR_NO_SUCH_USER_FOUND",
  ERROR_FIELDS_MISSING: "ERROR_FIELDS_MISSING"
}
